- name: Deploy EFK stack to Kubernetes
  hosts: master_server
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:
    - name: Ensure 'logging' namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: logging
        state: present

    - name: Deploy Elasticsearch
      include_role:
        name: elasticsearch

    - name: Deploy Kibana
      include_role:
        name: kibana

    - name: Deploy Fluentd
      include_role:
        name: fluentd