- name: Run Elasticsearch container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    state: started
    restart_policy: always
    env:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    published_ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

- name: Create docker volume for elasticsearch
  docker_volume:
    name: es_data