global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prom'

# remote_read:
#  - url: http://localhost:9090/api/v1/read

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: [
      'localhost:9090'
    ]

  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s 
    static_configs:
      - targets: ['192.168.113.111:30101', '192.168.113.112:30102']