# roles/fluentd/tasks/main.yml
- name: Create Fluentd configmap
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'files/fluentd-configmap.yaml') }}"

- name: Deploy Fluentd
  kubernetes.core.k8s:
    state: present
    definition: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: fluentd
        namespace: logging
      spec:
        selector:
          matchLabels:
            app: fluentd
        template:
          metadata:
            labels:
              app: fluentd
          spec:
            containers:
              - name: fluentd
                image: fluent/fluentd-kubernetes-daemonset:v1.14.2-debian-elasticsearch7-1.0
                env:
                  - name: FLUENT_ELASTICSEARCH_HOST
                    value: "elasticsearch"
                  - name: FLUENT_ELASTICSEARCH_PORT
                    value: "9200"
                volumeMounts:
                  - name: varlog
                    mountPath: /var/log
                  - name: containers
                    mountPath: /var/lib/docker/containers
                    readOnly: true
                  - name: config-volume
                    mountPath: /fluentd/etc/
            volumes:
              - name: varlog
                hostPath:
                  path: /var/log
              - name: containers
                hostPath:
                  path: /var/lib/docker/containers
              - name: config-volume
                configMap:
                  name: fluentd-config
