apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
stringData:
  DB_URL: "jdbc:mysql://mysql-service.database.svc.cluster.local:3306/vdt"
  DB_USERNAME: "phat"
  DB_PASSWORD: "15122004"
  ROOT_USERNAME: "root"
  ROOT_PASSWORD: "15122004"
  DATABASE_NAME: "vdt"
  
  # Additional useful connection strings
  mysql-root-password: "root"
  mysql-password: "15122004"
  
  # Full connection string for applications
  connection-string: "mysql://phat:15122004@mysql-service.database.svc.cluster.local:3306/vdt"
